name: Deploy Order Service

on:
  push:
    paths:
      - 'apps/services/order-service/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Este paso utiliza el Deploy Hook de Render para el servicio de órdenes
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_ORDER_DEPLOY_HOOK }}
