name: Deploy Payment Service (LIN Cloud)

on:
  push:
    paths:
      - 'apps/services/payment-service/**'
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  PUBLISH_URL: ${{ secrets.LIN_CLOUD_URL_PAYMENT }}
  PUBLISH_KEY: ${{ secrets.LIN_CLOUD_KEY_PAYMENT }}
  ZIP_NAME: payment-service.zip

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file from Secrets
        run: |
          cd apps/services/payment-service
          echo "MP_ACCESS_TOKEN=${{ secrets.MP_ACCESS_TOKEN }}" > .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "ORDER_SERVICE_URL=${{ secrets.ORDER_SERVICE_URL }}" >> .env
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> .env
          echo "PORT=3001" >> .env

      - name: Zip project folder
        run: |
          cd apps/services/payment-service && zip -r ../../../${{ env.ZIP_NAME }} . -x "node_modules/*" "test-db.js"

      - name: Verify ZIP existence
        run: |
          if [ -f "${{ env.ZIP_NAME }}" ]; then
            echo "✅ ${{ env.ZIP_NAME }} generado correctamente."
          else
            echo "❌ Error: No se pudo generar el archivo ZIP."
            exit 1
          fi

      - name: Upload ZIP a LIN Cloud
        run: |
          curl -X POST \
            "${{ env.PUBLISH_URL }}/api/Publish?createRelease=true" \
            -H "accept: text/plain" \
            -H "Content-Type: multipart/form-data" \
            -H "Key: ${{ env.PUBLISH_KEY }}" \
            -F "file=@${{ env.ZIP_NAME }}"
